# bootloader.pyi for stubs #
from typing import Any

# Bootloader class stub
class Bootloader:
    devices: list
    kernelModule: str

    def __init__(self) -> None: ...
    def bootMsg(self, msg: str, d: float = 0.0) -> None: ...
    def runPost(self) -> None: ...
    def loadKernel(self) -> Any: ...
    def startKernel(self) -> None: ...

# top-level boot function stub
def Boot() -> None: ...
